packages:
  - ./
  - playground/
patchedDependencies:
  "@nuxt/module-builder": patches/@nuxt__module-builder.patch
allowUnusedPatches: true
settings:
  cleanupUnusedCatalogs: false
  catalogMode: strict
catalog:
  "@alanscodelog/commitlint-config": ^3.1.2
  "@alanscodelog/eslint-config": ^6.3.0
  "@alanscodelog/semantic-release-config": ^6.0.0
  "@alanscodelog/tsconfigs": ^6.2.0
  "@alanscodelog/utils": ^6.0.1
  "@alanscodelog/vite-config": ^0.0.6
  "@chromatic-com/storybook": ^3.2.7
  "@commitlint/cli": ^19.8.1
  "@iconify/json": ^2.2.379
  "@internationalized/date": ^3.9.0
  "@nuxt/eslint-config": ^1.9.0
  "@nuxt/kit": ^4.0.3
  "@nuxt/module-builder": ^1.0.2
  "@nuxt/schema": ^4.0.3
  "@nuxt/types": ^2.18.1
  "@nuxtjs/i18n": ^9.5.6
  "@playwright/test": =1.54.0
  "@rollup/plugin-node-resolve": ^16.0.1
  "@storybook/addon-a11y": ^8.6.14
  "@storybook/addon-actions": ^8.6.14
  "@storybook/addon-essentials": ^8.6.14
  "@storybook/addon-interactions": ^8.6.14
  "@storybook/addon-links": ^8.6.14
  "@storybook/addon-storysource": ^8.6.14
  "@storybook/blocks": ^8.6.14
  "@storybook/manager-api": ^8.6.14
  "@storybook/test": ^8.6.14
  "@storybook/test-runner": ^0.22.1
  "@storybook/vue3": ^8.6.14
  "@storybook/vue3-vite": ^8.6.14
  "@tailwindcss/cli": ^4.1.12
  "@tailwindcss/postcss": ^4.1.12
  "@tailwindcss/vite": ^4.1.12
  "@types/node": ^24.3.0
  "@vitejs/plugin-vue": ^6.0.1
  "@vue/runtime-core": ^3.5.20
  "@vue/runtime-dom": ^3.5.20
  "@vueuse/components": ^13.8.0
  "@vueuse/core": ^13.8.0
  "@witchcraft/nuxt-utils": ^0.3.6
  autoprefixer: ^10.4.21
  colord: ^2.9.3
  colorjs.io: 0.6.0-alpha.1
  concurrently: ^9.2.1
  defu: ^6.1.4
  eslint: ^9.34.0
  fast-glob: ^3.3.3
  http-server: ^14.1.1
  husky: ^9.1.7
  indexit: 2.1.0-beta.3
  madge: ^7.0.0
  metamorphosis: ^0.6.1
  nuxt: ^4.0.3
  playwright: =1.54.0
  playwright-core: =1.54.0
  reka-ui: ^2.5.0
  semantic-release: ^24.2.7
  storybook: ^8.6.14
  storybook-dark-mode: ^4.0.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  ts-node: ^10.9.2
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^28.8.0
  vite: ^7.1.3
  vite-tsconfig-paths: ^5.1.4
  vue: ^3.5.20
  vue-component-type-helpers: ^2.2.12
  vue-tsc: 3.0.6
  wait-on: ^8.0.4
