packages:
  - ./
  - playground/

allowUnusedPatches: true

catalog:
  '@alanscodelog/commitlint-config': ^3.1.2
  '@alanscodelog/eslint-config': ^6.3.1
  '@alanscodelog/semantic-release-config': ^6.0.2
  '@alanscodelog/tsconfigs': ^6.2.0
  '@alanscodelog/utils': ^6.0.2
  '@alanscodelog/vite-config': ^0.0.7
  '@chromatic-com/storybook': ^3.2.7
  '@commitlint/cli': ^20.4.1
  '@faker-js/faker': ^10.3.0
  '@iconify/json': ^2.2.437
  '@internationalized/date': ^3.11.0
  '@nuxt/eslint-config': ^1.14.0
  '@nuxt/kit': ^4.3.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.3.1
  '@nuxt/types': ^2.18.1
  '@nuxtjs/i18n': ^9.5.6
  '@playwright/test': ^1.54.0
  '@rollup/plugin-node-resolve': ^16.0.3
  '@storybook/addon-a11y': ^8.6.15
  '@storybook/addon-actions': ^8.6.15
  '@storybook/addon-essentials': ^8.6.14
  '@storybook/addon-interactions': ^8.6.14
  '@storybook/addon-links': ^8.6.15
  '@storybook/addon-storysource': ^8.6.14
  '@storybook/blocks': ^8.6.14
  '@storybook/manager-api': ^8.6.14
  '@storybook/test': ^8.6.15
  '@storybook/test-runner': ^0.22.1
  '@storybook/vue3': ^8.6.15
  '@storybook/vue3-vite': ^8.6.15
  '@tailwindcss/cli': ^4.1.18
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/vue-virtual': ^3.13.18
  '@types/node': ^24.10.12
  '@vitejs/plugin-vue': ^6.0.4
  '@vue/runtime-core': ^3.5.27
  '@vue/runtime-dom': ^3.5.27
  '@vueuse/components': ^13.9.0
  '@vueuse/core': ^13.9.0
  '@witchcraft/nuxt-utils': ^0.3.6
  autoprefixer: ^10.4.24
  colord: ^2.9.3
  colorjs.io: 0.6.0-alpha.1
  concurrently: ^9.2.1
  defu: ^6.1.4
  eslint: ^9.39.2
  fast-glob: ^3.3.3
  http-server: ^14.1.1
  husky: ^9.1.7
  indexit: 2.1.0-beta.3
  madge: ^7.0.0
  metamorphosis: ^0.6.1
  nuxt: ^4.3.1
  playwright: ^1.54.0
  playwright-core: ^1.54.0
  reka-ui: ^2.8.0
  semantic-release: ^24.2.9
  storybook: ^8.6.15
  storybook-dark-mode: ^4.0.2
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  ts-node: ^10.9.2
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unplugin-icons: ^22.5.0
  unplugin-vue-components: ^28.8.0
  vite: ^7.3.1
  vite-tsconfig-paths: ^6.1.0
  vue: ^3.5.27
  vue-component-type-helpers: ^2.2.12
  vue-tsc: 3.2.4
  wait-on: ^8.0.5

patchedDependencies:
  '@nuxt/module-builder': patches/@nuxt__module-builder.patch

settings:
  catalogMode: strict
  cleanupUnusedCatalogs: false
