/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IIcRoundLogin: typeof import('~icons/ic/round-login')['default']
    ILucideKeyboard: typeof import('~icons/lucide/keyboard')['default']
    ILucideMinus: typeof import('~icons/lucide/minus')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    IMdiLocal: typeof import('~icons/mdi/local')['default']
    IPhUserDuotone: typeof import('~icons/ph/user-duotone')['default']
    IPhUserPlusDuotone: typeof import('~icons/ph/user-plus-duotone')['default']
    IRadixIconsTrash: typeof import('~icons/radix-icons/trash')['default']
  }
}
