import type { NumberFieldInputProps, NumberFieldRootEmits, NumberFieldRootProps } from "reka-ui";
import type { HTMLAttributes, InputHTMLAttributes } from "vue";
import type { EmitsToProps, TailwindClassProp } from "../../types/index.js";
declare const __VLS_export: import("vue").DefineComponent<{
    id?: string;
    max?: number;
    min?: number;
    step?: number;
    isValid?: (value: any) => boolean;
    inputProps?: NumberFieldInputProps & Omit<InputHTMLAttributes, "class" | "autocomplete"> & TailwindClassProp;
    rootProps?: NumberFieldRootProps & EmitsToProps<NumberFieldRootEmits> & Omit<HTMLAttributes, "class"> & TailwindClassProp;
    modelValue: number;
    key?: PropertyKey | undefined;
    name?: string;
    formatOptions?: Intl.NumberFormatOptions;
    as?: import("reka-ui").AsTag | import("vue").Component;
    disabled?: boolean;
    class?: unknown;
    locale?: string;
    style?: unknown;
    readonly?: boolean;
    required?: boolean;
    ref?: import("vue").VNodeRef | undefined;
    ref_for?: boolean | undefined;
    ref_key?: string | undefined;
    onVnodeBeforeMount?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    onVnodeMounted?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    onVnodeBeforeUpdate?: (((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void) | ((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void)[]) | undefined;
    onVnodeUpdated?: (((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void) | ((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void)[]) | undefined;
    onVnodeBeforeUnmount?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    onVnodeUnmounted?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    defaultValue?: number;
    asChild?: boolean;
    stepSnapping?: boolean;
    focusOnChange?: boolean;
    disableWheelChange?: boolean;
    invertWheelChange?: boolean;
}, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
    "update:modelValue": (value: number) => any;
}, string, import("vue").PublicProps, Readonly<{
    id?: string;
    max?: number;
    min?: number;
    step?: number;
    isValid?: (value: any) => boolean;
    inputProps?: NumberFieldInputProps & Omit<InputHTMLAttributes, "class" | "autocomplete"> & TailwindClassProp;
    rootProps?: NumberFieldRootProps & EmitsToProps<NumberFieldRootEmits> & Omit<HTMLAttributes, "class"> & TailwindClassProp;
    modelValue: number;
    key?: PropertyKey | undefined;
    name?: string;
    formatOptions?: Intl.NumberFormatOptions;
    as?: import("reka-ui").AsTag | import("vue").Component;
    disabled?: boolean;
    class?: unknown;
    locale?: string;
    style?: unknown;
    readonly?: boolean;
    required?: boolean;
    ref?: import("vue").VNodeRef | undefined;
    ref_for?: boolean | undefined;
    ref_key?: string | undefined;
    onVnodeBeforeMount?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    onVnodeMounted?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    onVnodeBeforeUpdate?: (((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void) | ((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void)[]) | undefined;
    onVnodeUpdated?: (((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void) | ((vnode: import("vue").VNode, oldVNode: import("vue").VNode) => void)[]) | undefined;
    onVnodeBeforeUnmount?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    onVnodeUnmounted?: (((vnode: import("vue").VNode) => void) | ((vnode: import("vue").VNode) => void)[]) | undefined;
    defaultValue?: number;
    asChild?: boolean;
    stepSnapping?: boolean;
    focusOnChange?: boolean;
    disableWheelChange?: boolean;
    invertWheelChange?: boolean;
}> & Readonly<{
    "onUpdate:modelValue"?: ((value: number) => any) | undefined;
}>, {
    max: number;
    min: number;
    isValid: (value: any) => boolean;
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
declare const _default: typeof __VLS_export;
export default _default;
//# sourceMappingURL=WNumberInput.vue.d.ts.map