name: Docs

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ docs ]

jobs:
  docs:
    if: "vars.ENABLE_DOCS == 'true'"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24.15.0']
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        timeout-minutes: 15
        uses: alanscodelog/actions/.github/actions/setup@master
        with:
          USE_LOCKFILE: ${{ vars.USE_LOCKFILE }}
          INSTALL_PLAYWRIGHT: true

      - name: Build
        uses: alanscodelog/actions/.github/actions/build@master
        with:
          test_script: "echo 'skipping tests'"

      - name: Deploy Docs
        uses: alanscodelog/actions/.github/actions/docs@master
        with:
          use_storybook: "true"
          # we do have a playground but it's currently for me to play
          use_playground: "false"
          use_nuxt_docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

