name: Release

on:
  push:
    branches: [ master, alpha, beta, build ]
  repository_dispatch:
    types: [ release ]

permissions:
  id-token: write

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24.15.0']
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        timeout-minutes: 15
        uses: alanscodelog/actions/.github/actions/setup@master
        with:
          USE_LOCKFILE: ${{ vars.USE_LOCKFILE }}
          INSTALL_PLAYWRIGHT: true

      - name: Build
        uses: alanscodelog/actions/.github/actions/build@master

      - name: Release
        uses: alanscodelog/actions/.github/actions/release@master
        with:
          ENABLE_RELEASE: ${{ vars.ENABLE_RELEASE == 'true' && github.ref != 'refs/heads/build' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
